// Generated by CoffeeScript 1.8.0
var SvgEdit;

SvgEdit = function() {
  var defaultAttrs, nameSpace, shapeDefultInfo;
  nameSpace = "http://www.w3.org/2000/svg";
  shapeDefultInfo = {
    rect: {
      x: 10,
      y: 10,
      width: 200,
      height: 100,
      rx: 0,
      ry: 0
    },
    circle: {
      cx: 200,
      cy: 200,
      r: 50
    },
    ellipse: {
      cx: 200,
      cy: 200,
      rx: 80,
      ry: 30
    },
    line: {
      x1: 10,
      y1: 10,
      x2: 100,
      y2: 100
    }
  };
  defaultAttrs = {
    fill: "#fff",
    stroke: "#000"
  };
  this.createSVG = function() {
    var svg;
    svg = document.createElementNS(nameSpace, 'svg');
    $(svg).attr({
      'width': '100%',
      'height': '100%'
    });
    $('#canvas').append(svg);
    return svg;
  };
  this.createShape = function(_svg) {
    $('#create').delegate('button', 'click', function() {
      var shape, shapeName;
      shapeName = $(this).attr('shape');
      shape = document.createElementNS(nameSpace, shapeName);
      $(shape).attr(shapeDefultInfo[shapeName]);
      _svg.appendChild(shape);
    });
  };
  this.init = function() {
    var svg;
    svg = this.createSVG();
    return this.createShape(svg);
  };
};

new SvgEdit().init();
